const contacts=[
    {
        name:'Владислав',
        phone:'+79164564545',
        email:'sad@mail.ru',
        sex:'male'
    },
    {
        name:'Николай',
        phone:'+7985454545',
        email:'sasdd324@mail.ru',
        sex:'male'
    },
    {
        name:'Елизавета',
        phone:'+7423454545',
        email:'ew43we@mail.ru',
        sex:'female'
    },
    {
        name:'Иван',
        phone:'+74566554545',
        email:'weeed@mail.ru',
        sex:'male'
    },
    {
        name:'Марина',
        phone:'+79876561212',
        email:'masdid@mail.ru',
        sex:'female'
    },
    {
        name:'Сергей',
        phone:'+79164561212',
        email:'sad@mail.ru',
        sex:'male'
    },
    {
        name:'Дмитрий',
        phone:'+79164512313',
        email:'s_asdad@mail.ru',
        sex:'male'
    },
    {
        name:'Никита',
        phone:'+791645546455',
        email:'weeewd@mail.ru',
        sex:'male'
    },
    {
        name:'Никита2',
        phone:'+798645546455',
        email:'wfdsd@mail.ru',
        sex:'male'
    },
]
module.exports = contacts